void VO_4_1_1( entity ent )
{
	//markswell: Viper Squad, our mission is simple.  Get in; Get Strauss; Get out. I'm not going to lie to you gentlemen, it's going to be nasty.  Give'em hell, Marines.
	aiSpeakWait( ent, "lipsync_vo_4_1_1" );
}

void VO_4_1_7( entity ent )
{
	//viper squad: Sir. Yes sir.
	aiSpeakWait( ent, "lipsync_vo_4_1_7" );
}

void VO_4_1_8( entity ent )
{
	//markswell: We're about thirty seconds from the infiltration point.  Feel free to --
	aiSpeakWait( ent, "lipsync_vo_4_1_8" );
}

void VO_4_1_9( entity ent )
{
	//markswell: What the hell?  Damage report!
	aiSpeakWait( ent, "lipsync_vo_4_1_9" );
}

void VO_4_1_10( entity ent )
{
	//marine7<Over Radio>: We're taking heavy fire, we've lost two port thrusters, and.
	aiSpeakWait( ent, "lipsync_vo_4_1_10" );
}

void VO_4_1_11( entity ent )
{
	//markswell: We're at the infiltration point, get -
	aiSpeakWait( ent, "lipsync_vo_4_1_11" );
}

void VO_4_1_12( entity ent )
{
	//markswell: Oh Shit!  Viper Squad.  Prepare of impact.  Prepare for im -
	aiSpeakWait( ent, "lipsync_vo_4_1_12" );
}

void VO_4_2_1( entity ent )
{
	//marine8: (Ser)geant?  Sergeant?  You're gonna be fine, Sir. 
	aiSpeakWait( ent, "lipsync_vo_4_2_1" );
}

void VO_4_2_2( entity ent )
{
	//marine11: Sir, breach point's ahead.  Stay low and go! 
	aiSpeakWait( ent, "lipsync_vo_4_2_2" );
}

void VO_4_2_2_1( entity ent )
{
	//marine10<Over Radio>: They're all over us!  Oh god - (Static)
	aiSpeakWait( ent, "lipsync_vo_4_2_2_1" );
}

void VO_4_2_2_2( entity ent )
{
	//marine10<Over Radio>: It's no good, Command.  We're gonna have to take the alternate route.
	aiSpeakWait( ent, "lipsync_vo_4_2_2_2" );
}

void VO_4_2_2_3( entity ent )
{
	//marine9<Over Radio>: Objective is lost, Command, please advise!
	aiSpeakWait( ent, "lipsync_vo_4_2_2_3" );
}

void VO_4_2_2_4( entity ent )
{
	//marine9<Over Radio>: Oh fuck!  They're already here!
	aiSpeakWait( ent, "lipsync_vo_4_2_2_4" );
}

void VO_4_2_2_5( entity ent )
{
	//marine8<Over Radio>: I need an evac now.  Now, dammit, now!
	aiSpeakWait( ent, "lipsync_vo_4_2_2_5" );
}

void VO_4_2_2_6( entity ent )
{
	//marine8<Over Radio>: We've lost contact with Raptor and Venom squads. 
	aiSpeakWait( ent, "lipsync_vo_4_2_2_6" );
}

void VO_4_2_2_7( entity ent )
{
	//marine7<Over Radio>: Raptor squad is down.  They ambushed us.  I'm the only one left, the entire squad was wiped out.
	aiSpeakWait( ent, "lipsync_vo_4_2_2_7" );
}

void VO_4_2_2_8( entity ent )
{
	//marine7<Over Radio>: Command, where is our fucking support?
	aiSpeakWait( ent, "lipsync_vo_4_2_2_8" );
}

void VO_4_2_2_9( entity ent )
{
	//marine6<Over Radio>: Eastern approach is stalled.  They've got us pinned in.  We're not gonna last long.
	aiSpeakWait( ent, "lipsync_vo_4_2_2_9" );
}

void VO_4_2_2_10( entity ent )
{
	//marine6<Over Radio>: Objective secure.
	aiSpeakWait( ent, "lipsync_vo_4_2_2_10" );
}

void VO_4_2_2_11( entity ent )
{
	//marine5<Over Radio>: Watch the turrets!  Watch the--
	aiSpeakWait( ent, "lipsync_vo_4_2_2_11" );
}

void VO_4_2_2_12( entity ent )
{
	//marine5<Over Radio>: They won't stop coming!  We've killed hundreds, they keep coming!
	aiSpeakWait( ent, "lipsync_vo_4_2_2_12" );
}

void VO_4_2_2_13( entity ent )
{
	//marine4<Over Radio>: This isn't an assault, Command.  It's a fucking massacre.
	aiSpeakWait( ent, "lipsync_vo_4_2_2_13" );
}

void VO_4_2_2_14( entity ent )
{
	//marine4<Over Radio>: Bunker eight-nine-bravo is clear!
	aiSpeakWait( ent, "lipsync_vo_4_2_2_14" );
}

void VO_4_2_2_15( entity ent )
{
	//marine3<Over Radio>: We've breached the Northern wall.  We're 'go' for infiltration.
	aiSpeakWait( ent, "lipsync_vo_4_2_2_15" );
}

void VO_4_2_2_16( entity ent )
{
	//marine3<Over Radio>: Mongoose squad is in position, awaiting further orders, Command.
	aiSpeakWait( ent, "lipsync_vo_4_2_2_16" );
}

void VO_4_2_2_17( entity ent )
{
	//marine2<Over Radio>: (Cough) Command (Cough) Sector two-four-nine is lost.  
	aiSpeakWait( ent, "lipsync_vo_4_2_2_17" );
}

void VO_4_2_2_18( entity ent )
{
	//marine2<Over Radio>: It's a clusterfuck, Command, two squads killed right in front of me.  We need an updated sitrep.  Now!
	aiSpeakWait( ent, "lipsync_vo_4_2_2_18" );
}

void VO_4_2_2_19( entity ent )
{
	//marine1<Over Radio>: They're all dead!  All of'em.  I'm not letting'em take me, Command.  You hear me?  They won't take me! (Gunshot)
	aiSpeakWait( ent, "lipsync_vo_4_2_2_19" );
}

void VO_4_2_2_20( entity ent )
{
	//marine1<Over Radio>: Oh shit!  They're taking us apart.  Twelfth mobile division was just fucking incinerated. You copy, Command?
	aiSpeakWait( ent, "lipsync_vo_4_2_2_20" );
}

void VO_4_2_3( entity ent )
{
	//marine1 : Get down.
	aiSpeakWait( ent, "lipsync_vo_4_2_3" );
}

void VO_4_2_4( entity ent )
{
	//marine2: Watch yourself.
	aiSpeakWait( ent, "lipsync_vo_4_2_4" );
}

void VO_4_2_5( entity ent )
{
	//marine3: We're taking heavy fire.
	aiSpeakWait( ent, "lipsync_vo_4_2_5" );
}

void VO_4_2_6( entity ent )
{
	//marine4: Move ahead, Sir.
	aiSpeakWait( ent, "lipsync_vo_4_2_6" );
}

void VO_4_2_7( entity ent )
{
	//marine5: Two more squads touched down, west side.
	aiSpeakWait( ent, "lipsync_vo_4_2_7" );
}

void VO_4_2_8( entity ent )
{
	//marine6: Stay down.
	aiSpeakWait( ent, "lipsync_vo_4_2_8" );
}

void VO_4_2_9( entity ent )
{
	//marine7: Careful, Sir.
	aiSpeakWait( ent, "lipsync_vo_4_2_9" );
}

void VO_4_2_10( entity ent )
{
	//marine8: Stay behind cover.
	aiSpeakWait( ent, "lipsync_vo_4_2_10" );
}

void VO_4_2_11( entity ent )
{
	//markswell<Over Radio>: Get moving, Marine.
	aiSpeakWait( ent, "lipsync_vo_4_2_11" );
}

void VO_4_2_12( entity ent )
{
	//markswell<Over Radio>: Breach those bunkers, Sergeant.
	aiSpeakWait( ent, "lipsync_vo_4_2_12" );
}

void VO_4_2_13( entity ent )
{
	//markswell<Over Radio>: You have your orders, Sergeant.  Find a way behind those turrets.
	aiSpeakWait( ent, "lipsync_vo_4_2_13" );
}

void VO_4_3_1( entity ent )
{
	//tak: Setting charges.
	aiSpeakWait( ent, "lipsync_vo_4_3_1" );
}

void VO_4_3_2( entity ent )
{
	//tak : Stand back.
	aiSpeakWait( ent, "lipsync_vo_4_3_2" );
}

void VO_4_3_3( entity ent )
{
	//tak: Clear!
	aiSpeakWait( ent, "lipsync_vo_4_3_3" );
}

void VO_4_4_1( entity ent )
{
	//tak: Sergeant?  Tiger squad's already entered the facility's transport hub - It's a massacre, Sir.  We've got to get them some backup
	aiSpeakWait( ent, "lipsync_vo_4_4_1" );
}

void VO_4_4_2( entity ent )
{
	//tak<Over Radio>: Setting spike.
	aiSpeakWait( ent, "lipsync_vo_4_4_2" );
}

void VO_4_4_3( entity ent )
{
	//tak: Establishing uplink.
	aiSpeakWait( ent, "lipsync_vo_4_4_3" );
}

void VO_4_4_4( entity ent )
{
	//tak: Hold on, we're hacking now.
	aiSpeakWait( ent, "lipsync_vo_4_4_4" );
}

void VO_4_4_5( entity ent )
{
	//darnell: We got incoming!  Keep'em off Tak!
	aiSpeakWait( ent, "lipsync_vo_4_4_5" );
}

void VO_4_4_6( entity ent )
{
	//darnell: That's it, we're in.
	aiSpeakWait( ent, "lipsync_vo_4_4_6" );
}

void VO_4_5_1( entity ent )
{
	//marine3: Tiger squad!
	aiSpeakWait( ent, "lipsync_vo_4_5_1" );
}

void VO_4_5_2( entity ent )
{
	//marine9: They were waiting for us!
	aiSpeakWait( ent, "lipsync_vo_4_5_2" );
}

void VO_4_5_3( entity ent )
{
	//marine4: Tiger squad, fall back.  Fall back!
	aiSpeakWait( ent, "lipsync_vo_4_5_3" );
}

void VO_4_5_4( entity ent )
{
	//marine12: What the hell is that?
	aiSpeakWait( ent, "lipsync_vo_4_5_4" );
}

void VO_4_5_5( entity ent )
{
	//marine12: Oh shit!
	aiSpeakWait( ent, "lipsync_vo_4_5_5" );
}

void VO_4_5_6( entity ent )
{
	//marine7: Sir?  We've got to help the rest of my squad, the damn squibs have cut'em off from the main assault force. Please, Sir.
	aiSpeakWait( ent, "lipsync_vo_4_5_6" );
}

void VO_4_5_7( entity ent )
{
	//marine12: They're good men, Sir.  We need to try.
	aiSpeakWait( ent, "lipsync_vo_4_5_7" );
}

void VO_4_6_1( entity ent )
{
	//markswell<Over Radio>: Sergeant!  Watch yourself, there's an automated turret ahead.  Armadillo squad took out its shield generators.  Finish the job, Marine.
	aiSpeakWait( ent, "lipsync_vo_4_6_1" );
}

void VO_4_6_2( entity ent )
{
	//marine10: Careful, Sergeant.  They. They were ready for us.  
	aiSpeakWait( ent, "lipsync_vo_4_6_2" );
}

void VO_4_8_1( entity ent )
{
	//marine8: Men, we got reinforcements.  Viper squad made it.
	aiSpeakWait( ent, "lipsync_vo_4_8_1" );
}

void VO_4_8_2( entity ent )
{
	//marines : (Cheers)
	aiSpeakWait( ent, "lipsync_vo_4_8_2" );
}

void VO_4_8_3( entity ent )
{
	//marine10: We're taking heavy causalities, Sergeant.  I've never seen anything like this, everything's going to shit. 
	aiSpeakWait( ent, "lipsync_vo_4_8_3" );
}

void VO_4_8_4( entity ent )
{
	//marine4: That was amazing, Sir.
	aiSpeakWait( ent, "lipsync_vo_4_8_4" );
}

void VO_4_8_7( entity ent )
{
	//marine11: I can't believe we made it through there.  Half second later and we'd have been trapped.
	aiSpeakWait( ent, "lipsync_vo_4_8_7" );
}

void VO_4_8_8( entity ent )
{
	//marine3: I don't even wanna think about.
	aiSpeakWait( ent, "lipsync_vo_4_8_8" );
}

void VO_4_8_9( entity ent )
{
	//marine2: Sir!  Have you talked with Dodson?  
	aiSpeakWait( ent, "lipsync_vo_4_8_9" );
}

void VO_4_8_9_1( entity ent )
{
	//marine6: Dekard!  I saw the Harvester go down, should'a guessed that was your work.  
	aiSpeakWait( ent, "lipsync_vo_4_8_9_1" );
}

void VO_4_8_9_2( entity ent )
{
	//marine6: I sent a demolition team out to breach into the facility, but we lost contact. If you can get there, you should be able to blow the door yourself. Good luck, Sergeant. 
	aiSpeakWait( ent, "lipsync_vo_4_8_9_2" );
}

void VO_4_8_10( entity ent )
{
	//marine8: Man, are we glad to see you.
	aiSpeakWait( ent, "lipsync_vo_4_8_10" );
}

void VO_4_8_11( entity ent )
{
	//marine8: I can't believe you made it here, you must be one hell of a soldier.
	aiSpeakWait( ent, "lipsync_vo_4_8_11" );
}

void VO_4_8_12( entity ent )
{
	//marine8: The Strogg have us pinned.  With you here, at least we have a chance.
	aiSpeakWait( ent, "lipsync_vo_4_8_12" );
}

void VO_4_8_13( entity ent )
{
	//marine10: Have you ever seen a mission of this scope?
	aiSpeakWait( ent, "lipsync_vo_4_8_13" );
}

void VO_4_8_14( entity ent )
{
	//marine10: So many men.  I hope its worth it.
	aiSpeakWait( ent, "lipsync_vo_4_8_14" );
}

void VO_4_8_15( entity ent )
{
	//marine10: I hope the other squads are having better luck.
	aiSpeakWait( ent, "lipsync_vo_4_8_15" );
}

void VO_4_8_16( entity ent )
{
	//marine4: Hey, you're Sergeant Dekard Chase.  Man, the rest of the guys'll never believe I met you.
	aiSpeakWait( ent, "lipsync_vo_4_8_16" );
}

void VO_4_8_17( entity ent )
{
	//marine4: You think I could get a transfer to Viper Squad?
	aiSpeakWait( ent, "lipsync_vo_4_8_17" );
}

void VO_4_8_18( entity ent )
{
	//marine4: How did you take down that Harvester?
	aiSpeakWait( ent, "lipsync_vo_4_8_18" );
}

void VO_4_8_19( entity ent )
{
	//marine6: We need to get into that facility, Sergeant.
	aiSpeakWait( ent, "lipsync_vo_4_8_19" );
}

void VO_4_8_20( entity ent )
{
	//marine6: The charges should be placed.
	aiSpeakWait( ent, "lipsync_vo_4_8_20" );
}

void VO_4_8_21( entity ent )
{
	//marine6: You have your orders, Marine.
	aiSpeakWait( ent, "lipsync_vo_4_8_21" );
}

void VO_4_8_22( entity ent )
{
	//marine11: Thanks for coming, Sir.
	aiSpeakWait( ent, "lipsync_vo_4_8_22" );
}

void VO_4_8_23( entity ent )
{
	//marine11: The Strogg blew the tunnel just as we got inside.
	aiSpeakWait( ent, "lipsync_vo_4_8_23" );
}

void VO_4_8_24( entity ent )
{
	//marine11: Have you seen the rest of Tiger Squad?
	aiSpeakWait( ent, "lipsync_vo_4_8_24" );
}

void VO_4_8_25( entity ent )
{
	//marine3: The tunnel just came down on top of us.
	aiSpeakWait( ent, "lipsync_vo_4_8_25" );
}

void VO_4_8_26( entity ent )
{
	//marine3: Barrington and I are the only ones that came out.
	aiSpeakWait( ent, "lipsync_vo_4_8_26" );
}

void VO_4_8_27( entity ent )
{
	//marine3: I hope the others are okay.
	aiSpeakWait( ent, "lipsync_vo_4_8_27" );
}

void VO_4_8_28( entity ent )
{
	//marine2: Ready when you are, Sir.
	aiSpeakWait( ent, "lipsync_vo_4_8_28" );
}

void VO_4_8_29( entity ent )
{
	//marine2: It's an honor to serve with you, Sir.
	aiSpeakWait( ent, "lipsync_vo_4_8_29" );
}

void VO_4_8_30( entity ent )
{
	//marine2: Let's bring it to'em.
	aiSpeakWait( ent, "lipsync_vo_4_8_30" );
}

void VO_4_9_1( entity ent )
{
	//marine11: Aw shit.  The fuses are blown, and the trigger relay is straight up fucked.  Its gonna take me a minute to get these ready.
	aiSpeakWait( ent, "lipsync_vo_4_9_1" );
}

void VO_4_9_2( entity ent )
{
	//darnell: Oh hell, is that what I think it is?
	aiSpeakWait( ent, "lipsync_vo_4_9_2" );
}

void VO_4_9_3( entity ent )
{
	//tak: We got incoming.
	aiSpeakWait( ent, "lipsync_vo_4_9_3" );
}

void VO_4_9_4( entity ent )
{
	//dekard: How many?
	aiSpeakWait( ent, "lipsync_vo_4_9_4" );
}

void VO_4_9_5( entity ent )
{
	//tak: Mother fucking all of them it looks like.
	aiSpeakWait( ent, "lipsync_vo_4_9_5" );
}

void VO_4_9_6( entity ent )
{
	//darnell: Shit.
	aiSpeakWait( ent, "lipsync_vo_4_9_6" );
}

void VO_4_9_8( entity ent )
{
	//trager: Watch my back guys.  Give me two minutes.
	aiSpeakWait( ent, "lipsync_vo_4_9_8" );
}

void VO_4_9_9( entity ent )
{
	//tak: Roger that.
	aiSpeakWait( ent, "lipsync_vo_4_9_9" );
}

void VO_4_9_10( entity ent )
{
	//trager: All right, here we go.  Keep'em off me, girls.
	aiSpeakWait( ent, "lipsync_vo_4_9_10" );
}

void VO_4_10_1( entity ent )
{
	//trager: First charge is ready.  Two more.
	aiSpeakWait( ent, "lipsync_vo_4_10_1" );
}

void VO_4_10_2( entity ent )
{
	//trager: That's two.
	aiSpeakWait( ent, "lipsync_vo_4_10_2" );
}

void VO_4_10_3( entity ent )
{
	//trager: That's the third!  Clear, clear, clear!
	aiSpeakWait( ent, "lipsync_vo_4_10_3" );
}

void VO_4_10_4( entity ent )
{
	//trager: Dammit, they're on me!
	aiSpeakWait( ent, "lipsync_vo_4_10_4" );
}

void VO_4_10_5( entity ent )
{
	//trager: I can't work like this.
	aiSpeakWait( ent, "lipsync_vo_4_10_5" );
}

void VO_4_10_6( entity ent )
{
	//trager: Keep'em off me!
	aiSpeakWait( ent, "lipsync_vo_4_10_6" );
}

void VO_4_10_7( entity ent )
{
	//darnell: We lost one!
	aiSpeakWait( ent, "lipsync_vo_4_10_7" );
}

void VO_4_10_8( entity ent )
{
	//darnell: Man down!
	aiSpeakWait( ent, "lipsync_vo_4_10_8" );
}

void VO_4_10_9( entity ent )
{
	//darnell: South wall!
	aiSpeakWait( ent, "lipsync_vo_4_10_9" );
}

void VO_4_10_10( entity ent )
{
	//darnell: Contact, East Side!
	aiSpeakWait( ent, "lipsync_vo_4_10_10" );
}

void VO_4_10_11( entity ent )
{
	//darnell: Watch the West!
	aiSpeakWait( ent, "lipsync_vo_4_10_11" );
}

void VO_4_10_12( entity ent )
{
	//darnell: 12 o'clock high, boys!
	aiSpeakWait( ent, "lipsync_vo_4_10_12" );
}

void VO_4_10_13( entity ent )
{
	//tak: Marine down!
	aiSpeakWait( ent, "lipsync_vo_4_10_13" );
}

void VO_4_10_14( entity ent )
{
	//tak: We need a medic!
	aiSpeakWait( ent, "lipsync_vo_4_10_14" );
}

void VO_4_10_15( entity ent )
{
	//tak: They're coming from the South wall.
	aiSpeakWait( ent, "lipsync_vo_4_10_15" );
}

void VO_4_10_16( entity ent )
{
	//tak: I got Strogg, East side.
	aiSpeakWait( ent, "lipsync_vo_4_10_16" );
}

void VO_4_10_17( entity ent )
{
	//tak: West side!
	aiSpeakWait( ent, "lipsync_vo_4_10_17" );
}

void VO_4_10_18( entity ent )
{
	//tak: They're coming in from above!
	aiSpeakWait( ent, "lipsync_vo_4_10_18" );
}

void VO_4_10_19( entity ent )
{
	//marine1: Contact!
	aiSpeakWait( ent, "lipsync_vo_4_10_19" );
}

void VO_4_10_20( entity ent )
{
	//marine1: Is that all you bitches got?
	aiSpeakWait( ent, "lipsync_vo_4_10_20" );
}

void VO_4_10_21( entity ent )
{
	//marine1: Bet'cha didn't count on this, huh, Squibs?
	aiSpeakWait( ent, "lipsync_vo_4_10_21" );
}

void VO_4_10_22( entity ent )
{
	//marine2: Bring it, Squibs!
	aiSpeakWait( ent, "lipsync_vo_4_10_22" );
}

void VO_4_10_23( entity ent )
{
	//marine2: They ain't half as tough as they are ugly.
	aiSpeakWait( ent, "lipsync_vo_4_10_23" );
}

void VO_4_10_24( entity ent )
{
	//marine2: There's more where that came from.
	aiSpeakWait( ent, "lipsync_vo_4_10_24" );
}

void VO_4_10_25( entity ent )
{
	//marine3: You'll have to do better than that.
	aiSpeakWait( ent, "lipsync_vo_4_10_25" );
}

void VO_4_10_26( entity ent )
{
	//marine3: Want some of this?
	aiSpeakWait( ent, "lipsync_vo_4_10_26" );
}

void VO_4_10_27( entity ent )
{
	//marine3: Strogg down.
	aiSpeakWait( ent, "lipsync_vo_4_10_27" );
}

void VO_4_11_1( entity ent )
{
	//darnell: Sarge, Eagle and Cougar squads are in place, all we gotta do is find a security center and let'em in.
	aiSpeakWait( ent, "lipsync_vo_4_11_1" );
}

void VO_4_12_1( entity ent )
{
	//tak: It's no good, Sergeant.  We don't have enough explosives left to blast the door.
	aiSpeakWait( ent, "lipsync_vo_4_12_1" );
}

void VO_4_13_1( entity ent )
{
	//markswell<Over Radio>: Good job, Marine.  Eagle and Cougar squads are entering now.  Meet up with Viper and proceed into the main prison.  We have to get Strauss before it's too late.
	aiSpeakWait( ent, "lipsync_vo_4_13_1" );
}

void VO_4_14_1( entity ent )
{
	//darnell: Sergeant! Glad to see you.  We're the first squad to make it this far.
	aiSpeakWait( ent, "lipsync_vo_4_14_1" );
}

void VO_4_14_2( entity ent )
{
	//tak: We've secured most of the area; all that's left is getting into the main prison wing.  
	aiSpeakWait( ent, "lipsync_vo_4_14_2" );
}

